version: '3'

services:
  bot:
    restart: always
    build: ./bot
    env_file: ./bot/.env
    depends_on: model

  model:
    restart: always
    image: dmitrydity/dialo_bot:latest
    env_file: model_deploying/.env
